### ISSUE TITLE
Off-label use of HKDF

### ISSUE THREAD

**Issue by Sc00bz** [FiloSottile/go-cpace-ristretto255#2]
For HKDF, you can do extract-and-expand or just expand. Doing just extract is not HKDF. I could not find any mention of skipping the expand part in the [RFC](https://tools.ietf.org/html/rfc5869). Also [Go docs](https://godoc.org/golang.org/x/crypto/hkdf#Extract) state "Extract generates a pseudorandom key for use with Expand from an input secret and an optional independent salt. Only use this function if you need to reuse the extracted key with multiple Expand invocations and different context values."

I don't see anything wrong with using HMAC as a KDF. Which is what you are doing as `HKDF_extract(ikm, salt)` is `HMAC(key:salt, data:ikm)`, but it is not HKDF.

**Comment by FiloSottile** [comment]
Fair enough. I'll just specify it in terms of HMAC instead.
